### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by tremby** [marksteele/netlify-serverless-oauth2-backend#1]
Might it be possible to support Gitlab (self-hosted, especially) authentication once the Netlify Gitlab support is merged?

**Comment by marksteele** [comment]
Gitlab supports the implicit OAuth2 flow, I believe running this wouldn't be necessary. This can be done all in-browser (in netlify code).

See here: https://docs.gitlab.com/ee/api/oauth2.html#implicit-grant

**Comment by tremby** [comment]
Oh, great! I did read mentions of implicit Auth in the ticket I linked (I
believe they were saying that was something they'd add support for later)
but didn't realize what it was. Thanks.

>
