### ISSUE TITLE
Is there anyway to use cognito credentials to authenticate with github?

### ISSUE THREAD

**Issue by shawnmmatthews** [marksteele/netlify-serverless-oauth2-backend#4]
Hey Mark,

Thanks for the excellent blog post and auth provider! I built out your Hugo setup and things work great. I'm working on a Gatsby setup now, and was wondering if it is possible to use Cognito credentials to authenticate with Github in a similar manner. So one Github account to many Cognito users. I'd love to use a Cognito User Pool trigger via Serverless to run a Lambda, check for an admin role, and authenticate if found. I was working on this from a different direction using a self hosted copy of Git-Gateway and just trying to effectively replace GoTrue with a Node based function, but have not been very successful... yet. I figured it might be worth reaching out.

I'm trying to do this in order to use NetlifyCMS for static content creation, and still have Amplify available to handle dynamic and user based content in Gatsby client side.

Thanks!
Shawn

**Comment by amitgandhinz** [comment]
@shawnmmatthews did you make any progress with this?  I am looking for something similar where users authenticate on the site with Cognito stored credentials, which then gives them access to the GitHub repo via the CMS.  I don't want to run a separate git-gateway since I'm trying to stay completely serverless to keep costs down.

**Comment by shawnmmatthews** [comment]
Nope. I ended up just hosting with Netlify. So far so good. I didn't want to get into hosting two Go based servers to keep this running on my own.

**Comment by amitgandhinz** [comment]
yeh my problem with Netlify is it can get pretty costly with invite only users.  Im also lookin to avoid hosting servers.  I'll keep digging for a solution here.
