### ISSUE TITLE
Os.tmpDir deprecated in favor of Os.tmpdir

### ISSUE THREAD

**Issue by manulari** [marksteele/netlify-serverless-oauth2-backend#6]
sls deploy fails with 
```
TypeError: Os.tmpDir is not a function
      at Object.<anonymous> (/home/manu/forothers/christianA/netlify-serverless-oauth2-backend/node_modules/hapi/lib/defaults.js:52:25)
```

changing Os.tmpDir to Os.tmpdir at that location seems to fix that error

**Comment by manulari** [comment]
No idea what the right way to fix this is. Upstream hapi seems to fix the call to Os.tmpDir / Os.tmpdir in version 16.0.0, according to their changelog.
Would that (or a higher) version be compatible with the rest of the packages used here?
(Sorry, I'm a stranger to the whole node ecosystem.)

**Comment by kellym** [comment]
Looks like this isn't maintained anymore, but upgrading `serverless-offline` resolves the issue.

**Comment by marksteele** [comment]
PRs are welcome
